import type { HospitalService, HospitalFacility } from '../types';

export const INITIAL_SERVICES: HospitalService[] = [
  {
    id: 'emergency-care',
    name: 'Emergency Care (24×7)',
    description: 'Urgent medical assistance and emergency support. Call the hospital directly for immediate guidance.',
    category: 'emergency',
    iconName: 'Activity',
    displayOrder: 1,
    featured: true,
    active: true,
    isEmergency: true,
  },
  {
    id: 'obstetrics-gynaecology',
    name: 'Obstetrics & Gynaecology',
    description: "Women's health, pregnancy care, maternity services and gynaecological consultations.",
    category: 'maternity',
    iconName: 'Baby',
    displayOrder: 2,
    featured: true,
    active: true,
  },
  {
    id: 'pediatrics',
    name: 'Pediatrics',
    description: 'Medical care and consultations for infants, children and adolescents.',
    category: 'general',
    iconName: 'HeartPulse',
    displayOrder: 3,
    featured: true,
    active: true,
  },
  {
    id: 'general-medicine',
    name: 'General Medicine',
    description: 'Consultation, diagnosis and management of common adult medical conditions.',
    category: 'general',
    iconName: 'Stethoscope',
    displayOrder: 4,
    featured: true,
    active: true,
  },
  {
    id: 'general-surgery',
    name: 'General Surgery',
    description: 'Surgical consultation and care based on clinical assessment and available facilities.',
    category: 'specialist',
    iconName: 'ShieldAlert',
    displayOrder: 5,
    featured: true,
    active: true,
  },
  {
    id: 'orthopaedic-care',
    name: 'Orthopaedic Care',
    description: 'Assessment and treatment support for bone, joint and musculoskeletal conditions.',
    category: 'specialist',
    iconName: 'Bone',
    displayOrder: 6,
    active: true,
  },
  {
    id: 'urology',
    name: 'Urology',
    description: 'Specialist consultation for urinary and related urological conditions.',
    category: 'specialist',
    iconName: 'ShieldCheck',
    displayOrder: 7,
    active: true,
  },
  {
    id: 'ent',
    name: 'ENT',
    description: 'Evaluation and treatment support for ear, nose and throat conditions.',
    category: 'specialist',
    iconName: 'Ear',
    displayOrder: 8,
    active: true,
  },
  {
    id: 'cardiology',
    name: 'Cardiology',
    description: 'Cardiac consultation and diagnostic support as available at the hospital.',
    category: 'specialist',
    iconName: 'Heart',
    displayOrder: 9,
    active: true,
  },
  {
    id: 'dental-care',
    name: 'Dental Care',
    description: 'Dental consultation and treatment services as provided by the hospital.',
    category: 'specialist',
    iconName: 'Smile',
    displayOrder: 10,
    active: true,
  },
  {
    id: 'xray-ecg',
    name: 'X-Ray & ECG',
    description: 'Diagnostic support including X-ray and electrocardiogram services.',
    category: 'diagnostic',
    iconName: 'Radio',
    displayOrder: 11,
    active: true,
  },
  {
    id: 'laboratory-facility',
    name: 'Laboratory Facility',
    description: 'Laboratory and diagnostic testing support based on available facilities.',
    category: 'diagnostic',
    iconName: 'FlaskConical',
    displayOrder: 12,
    active: true,
  },
  {
    id: 'pharmacy',
    name: 'Pharmacy',
    description: 'Medicine and prescription support for admitted and outpatient patients.',
    category: 'diagnostic',
    iconName: 'Pill',
    displayOrder: 13,
    active: true,
  },
  {
    id: 'ambulance-facility',
    name: 'Ambulance Facility',
    description: 'Ambulance support for patient transportation, subject to availability.',
    category: 'diagnostic',
    iconName: 'Ambulance',
    displayOrder: 14,
    active: true,
  },
  {
    id: 'regular-opd',
    name: 'Regular Outpatient Check-up',
    description: 'Routine outpatient consultations and follow-up care.',
    category: 'general',
    iconName: 'ClipboardCheck',
    displayOrder: 15,
    active: true,
  },
];

export const INITIAL_FACILITIES: HospitalFacility[] = [
  {
    id: 'facility-pharmacy',
    name: 'Pharmacy',
    description: 'Medicine and prescription support for admitted and outpatient patients.',
    iconName: 'Pill',
    displayOrder: 1,
    active: true,
  },
  {
    id: 'facility-xray-ecg',
    name: 'X-Ray & ECG',
    description: 'Diagnostic support including X-ray and electrocardiogram services.',
    iconName: 'Radio',
    displayOrder: 2,
    active: true,
  },
  {
    id: 'facility-laboratory',
    name: 'Laboratory Facility',
    description: 'Laboratory and diagnostic testing support based on available facilities.',
    iconName: 'FlaskConical',
    displayOrder: 3,
    active: true,
  },
  {
    id: 'facility-ambulance',
    name: 'Ambulance Facility',
    description: 'Ambulance support for patient transportation, subject to availability.',
    iconName: 'Ambulance',
    displayOrder: 4,
    active: true,
  },
];

export const SERVICE_CATEGORIES = [
  { key: 'all', label: 'All Services' },
  { key: 'maternity', label: "Maternity & Women's Health" },
  { key: 'general', label: 'General & Family Care' },
  { key: 'specialist', label: 'Specialist Consultations' },
  { key: 'diagnostic', label: 'Diagnostics & Facilities' },
  { key: 'emergency', label: 'Emergency (24×7)' },
] as const;
