import type { Doctor } from '../types';

export const INITIAL_DOCTORS: Doctor[] = [
  // FEATURED CONSULTANTS (Category 1: With Approved Profile Images)
  {
    id: 'dr-syeda-maternity',
    name: 'Dr. Syeda Fatima',
    designation: 'Consultant Obstetrician & Gynaecologist',
    specialization: 'Obstetrics & Gynaecology',
    qualification: 'MBBS, DGO, DNB (OBG)',
    profileType: 'featured',
    imageUrl: 'https://images.unsplash.com/photo-1594824813596-f9479e0004ff?auto=format&fit=crop&w=600&q=80',
    description: 'Consultant in maternal healthcare, pregnancy management, antenatal care, and gynaecological consultations.',
    displayOrder: 1,
    featured: true,
    active: true,
  },
  {
    id: 'dr-mohammed-general-medicine',
    name: 'Dr. Mohammed Arif',
    designation: 'Consultant Physician',
    specialization: 'General Medicine',
    qualification: 'MBBS, MD (General Medicine)',
    profileType: 'featured',
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80',
    description: 'Consultation and clinical management for common adult medical conditions, chronic illnesses, and preventive health.',
    displayOrder: 2,
    featured: true,
    active: true,
  },
  {
    id: 'dr-rahul-pediatrics',
    name: 'Dr. Rahul Patil',
    designation: 'Consultant Paediatrician',
    specialization: 'Paediatrics',
    qualification: 'MBBS, DCH, DNB (Paediatrics)',
    profileType: 'featured',
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80',
    description: 'Specialist in infant and child healthcare, developmental assessments, and pediatric consultations.',
    displayOrder: 3,
    featured: true,
    active: true,
  },
  {
    id: 'dr-ayesha-gynae',
    name: 'Dr. Ayesha Siddiqua',
    designation: 'Consultant Gynaecologist',
    specialization: 'Obstetrics & Gynaecology',
    qualification: 'MBBS, MS (OBG)',
    profileType: 'featured',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80',
    description: 'Women’s health consultations, family planning guidance, and routine gynaecological screenings.',
    displayOrder: 4,
    featured: true,
    active: true,
  },

  // MEDICAL DIRECTORY (Category 2: Without Profile Images - Clean Typographic Presentation)
  {
    id: 'dr-zaheer-surgery',
    name: 'Dr. Zaheer Ahmed',
    designation: 'Consultant General Surgeon',
    specialization: 'General Surgery',
    qualification: 'MBBS, MS (General Surgery)',
    profileType: 'directory',
    displayOrder: 5,
    active: true,
  },
  {
    id: 'dr-praveen-ortho',
    name: 'Dr. Praveen Kumar',
    designation: 'Consultant Orthopaedic Surgeon',
    specialization: 'Orthopaedics',
    qualification: 'MBBS, MS (Ortho), D.Ortho',
    profileType: 'directory',
    displayOrder: 6,
    active: true,
  },
  {
    id: 'dr-abdul-urology',
    name: 'Dr. Abdul Qadeer',
    designation: 'Consultant Urologist',
    specialization: 'Urology',
    qualification: 'MBBS, MS, M.Ch (Urology)',
    profileType: 'directory',
    displayOrder: 7,
    active: true,
  },
  {
    id: 'dr-santosh-ent',
    name: 'Dr. Santosh Biradar',
    designation: 'Consultant ENT Surgeon',
    specialization: 'ENT',
    qualification: 'MBBS, MS (ENT)',
    profileType: 'directory',
    displayOrder: 8,
    active: true,
  },
  {
    id: 'dr-imran-cardiology',
    name: 'Dr. Imran Khan',
    designation: 'Visiting Cardiologist',
    specialization: 'Cardiology',
    qualification: 'MBBS, MD, DM (Cardiology)',
    profileType: 'directory',
    displayOrder: 9,
    active: true,
  },
  {
    id: 'dr-neha-dental',
    name: 'Dr. Neha Kulkarni',
    designation: 'Dental Surgeon',
    specialization: 'Dental Care',
    qualification: 'BDS, MDS',
    profileType: 'directory',
    displayOrder: 10,
    active: true,
  },
  {
    id: 'dr-sunil-anaesthesia',
    name: 'Dr. Sunil Deshmukh',
    designation: 'Consultant Anaesthesiologist',
    specialization: 'Anaesthesia',
    qualification: 'MBBS, DA, DNB (Anaesthesia)',
    profileType: 'directory',
    displayOrder: 11,
    active: true,
  },
  {
    id: 'dr-duty-medical-officer-1',
    name: 'Dr. M. Farooq',
    designation: 'Duty Medical Officer',
    specialization: 'General Medicine',
    qualification: 'MBBS',
    profileType: 'directory',
    displayOrder: 12,
    active: true,
  },
  {
    id: 'dr-duty-medical-officer-2',
    name: 'Dr. Deepa S.',
    designation: 'Duty Medical Officer',
    specialization: 'General Medicine',
    qualification: 'MBBS',
    profileType: 'directory',
    displayOrder: 13,
    active: true,
  },
];
