import type { GalleryItem } from '../types';

export const INITIAL_GALLERY: GalleryItem[] = [
  {
    id: 'gallery-maternity-suite',
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80',
    title: 'Maternity Care & Recovery Suite',
    description: 'Sanitized maternal care room designed for comfort, patient rest, and dedicated post-delivery care.',
    category: 'Maternity Care',
    featured: true,
    displayOrder: 1,
    active: true,
    createdAt: '2026-01-15T10:00:00Z',
    altText: 'Clean and sanitized maternity patient recovery room at Deccan Care Hospital',
    aspectRatio: '16:10',
  },
  {
    id: 'gallery-consultation-room',
    imageUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80',
    title: 'Outpatient Consultation Desk',
    description: 'Private consultation space for general medicine, obstetric reviews, and clinical evaluations.',
    category: 'Consultations',
    featured: true,
    displayOrder: 2,
    active: true,
    createdAt: '2026-01-18T11:30:00Z',
    altText: 'Doctor outpatient consultation desk and clinical review space',
    aspectRatio: '4:3',
  },
  {
    id: 'gallery-diagnostic-lab',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    title: 'Diagnostic Support & Laboratory',
    description: 'Laboratory testing and diagnostics unit supporting routine investigations and urgent sample processing.',
    category: 'Diagnostics & Facilities',
    featured: true,
    displayOrder: 3,
    active: true,
    createdAt: '2026-01-20T09:15:00Z',
    altText: 'Diagnostic laboratory and clinical investigation equipment',
    aspectRatio: '4:3',
  },
  {
    id: 'gallery-xray-ecg-suite',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
    title: 'X-Ray & ECG Facility',
    description: 'Diagnostic imaging and electrocardiogram services supporting outpatient and emergency evaluations.',
    category: 'Diagnostics & Facilities',
    featured: false,
    displayOrder: 4,
    active: true,
    createdAt: '2026-01-22T14:00:00Z',
    altText: 'Clinical diagnostic room and medical equipment',
    aspectRatio: '4:3',
  },
  {
    id: 'gallery-pharmacy-counter',
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=800&q=80',
    title: 'Hospital Pharmacy Dispensing',
    description: 'In-house pharmacy counter dispensing prescribed medications for admitted and outpatient patients.',
    category: 'Hospital Facilities',
    featured: false,
    displayOrder: 5,
    active: true,
    createdAt: '2026-01-25T16:20:00Z',
    altText: 'Hospital pharmacy dispensary counter with medications',
    aspectRatio: '4:3',
  },
  {
    id: 'gallery-maternity-guidance',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80',
    title: 'Antenatal & Maternity Consultation',
    description: 'Obstetric and maternal health guidance helping expectant mothers throughout pregnancy.',
    category: 'Maternity Care',
    featured: false,
    displayOrder: 6,
    active: true,
    createdAt: '2026-01-28T10:45:00Z',
    altText: 'Healthcare provider consulting with expectant mother in clinical room',
    aspectRatio: '4:3',
  },
];
